### ISSUE TITLE
hwameistor-local-storage CrashLoopBackOff

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor#690]
Output of `lsblk`:
```time="2023-03-15T03:02:37Z" level=debug msg="Reconciling a VolumeGroup" func=ReconcileVolumeGroup file="manager.go:344" Module=LocalVolumeGroupManager lvg=5356b6fe-597c-48c0-b680-bdce7c135ca5
fatal error: concurrent map iteration and map write

goroutine 143 [running]:
reflect.mapiternext(0x4b9a8f?)
        /usr/local/go/src/runtime/map.go:1380 +0x19
reflect.(*MapIter).Next(0xc00254aaf8?)
        /usr/local/go/src/reflect/value.go:1846 +0x7e
internal/fmtsort.Sort({0x16750a0?, 0xc0001bbd10?, 0x44?})
        /usr/local/go/src/internal/fmtsort/sort.go:62 +0x1f3
fmt.(*pp).printValue(0xc000a2f790, {0x16750a0?, 0xc0001bbd10?, 0x4eef48?}, 0x76, 0x0)
        /usr/local/go/src/fmt/print.go:800 +0xa0b
fmt.(*pp).printArg(0xc000a2f790, {0x16750a0?, 0xc0001bbd10}, 0x76)
        /usr/local/go/src/fmt/print.go:743 +0x756
fmt.(*pp).doPrint(0xc000a2f790, {0xc00254af28?, 0x1, 0x1?})
        /usr/local/go/src/fmt/print.go:1188 +0x1a9
fmt.Sprint({0xc00254af28, 0x1, 0x1})
        /usr/local/go/src/fmt/print.go:259 +0x45
github.com/sirupsen/logrus.(*TextFormatter).appendValue(0x0?, 0x18c2b00?, {0x16750a0?, 0xc0001bbd10?})
        /go/src/github.com/hwameistor/hwameistor/vendor/github.com/sirupsen/logrus/text_formatter.go:331 +0x73
github.com/sirupsen/logrus.(*TextFormatter).appendKeyValue(0x16b1180?, 0xc001b7ca80, {0x18c2b00?, 0x6?}, {0x16750a0, 0xc0001bbd10})
        /go/src/github.com/hwameistor/hwameistor/vendor/github.com/sirupsen/logrus/text_formatter.go:325 +0x9e
github.com/sirupsen/logrus.(*TextFormatter).Format(0xc000115800, 0xc001e840e0)
        /go/src/github.com/hwameistor/hwameistor/vendor/github.com/sirupsen/logrus/text_formatter.go:224 +0x1477
github.com/sirupsen/logrus.(*Entry).write(0xc001e840e0)
        /go/src/github.com/hwameistor/hwameistor/vendor/github.com/sirupsen/logrus/entry.go:289 +0xa5
github.com/sirupsen/logrus.(*Entry).log(0xc001e84070, 0x5, {0xc001e6e070, 0xd})
        /go/src/github.com/hwameistor/hwameistor/vendor/github.com/sirupsen/logrus/entry.go:252 +0x445
github.com/sirupsen/logrus.(*Entry).Log(0xc001e84070, 0x5, {0xc00254b6e0?, 0x7?, 0xc00254b7f8?})
        /go/src/github.com/hwameistor/hwameistor/vendor/github.com/sirupsen/logrus/entry.go:304 +0x4f
github.com/sirupsen/logrus.(*Entry).Debug(...)
        /go/src/github.com/hwameistor/hwameistor/vendor/github.com/sirupsen/logrus/entry.go:313
github.com/hwameistor/hwameistor/pkg/local-storage/member/controller/volumegroup.(*manager).debug(0xc000734380)
        /go/src/github.com/hwameistor/hwameistor/pkg/local-storage/member/controller/volumegroup/manager.go:85 +0x1e6
github.com/hwameistor/hwameistor/pkg/local-storage/member/controller/volumegroup.(*manager).addLocalVolume(0xc000734380, 0xc003141200)
        /go/src/github.com/hwameistor/hwameistor/pkg/local-storage/member/controller/volumegroup/manager.go:532 +0x8af
github.com/hwameistor/hwameistor/pkg/local-storage/member/controller/volumegroup.(*manager).handleLocalVolumeEventAdd(0xc000734380, {0x188ce60?, 0xc003141200})
        /go/src/github.com/hwameistor/hwameistor/pkg/local-storage/member/controller/volumegroup/manager.go:156 +0x45
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
        /go/src/github.com/hwameistor/hwameistor/vendor/k8s.io/client-go/tools/cache/controller.go:231
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /go/src/github.com/hwameistor/hwameistor/vendor/k8s.io/client-go/tools/cache/shared_informer.go:777 +0x134
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x6567616e61?)
        /go/src/github.com/hwameistor/hwameistor/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00079b738?, {0x1b22700, 0xc000a16270}, 0x1, 0xc00068e8a0)
        /go/src/github.com/hwameistor/hwameistor/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x6539313262316639?, 0x3b9aca00, 0x0, 0x61?, 0xc00079b788?)
        /go/src/github.com/hwameistor/hwameistor/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/src/github.com/hwameistor/hwameistor/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000a08380?)
        /go/src/github.com/hwameistor/hwameistor/vendor/k8s.io/client-go/tools/cache/shared_informer.go:771 +0x6b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
        /go/src/github.com/hwameistor/hwameistor/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /go/src/github.com/hwameistor/hwameistor/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x85
```

**Comment by FloatXD** [comment]
fix in https://github.com/hwameistor/hwameistor/pull/692 https://github.com/hwameistor/hwameistor/pull/691
